####################################
# Start Substitutions
####################################

substitutions:
# Replace name with you sensor name
#  name: st-occ-2410
#  friendly_name: "ST Occ 2410"
  comment_text: "Generally Unstable and Poorly Produced Inventions - Multi-target Human Presence and Occupancy Sensor by Zone (ESP32/LD2450) with Temperature, and Humidity"
  project_name: "GUPPI.MT-OCC-2450-28"
  project_version: "25.2.19.1"
# **IMPORTANT** - Add API key here for copy/paste convenience
#  api_key: "abcxyz123="
# Specify below pin numbers for UART, GPIO, and I2C connections
# Delete if not needed
#  tx_pin_uart: GPIO21
#  rx_pin_uart: GPIO20
#  light_gpio: GPIO2
#  motion_gpio: GPIO4
#  sda_pin_i2c: GPIO6
#  scl_pin_i2c: GPIO7

####################################
# End Substitutions
####################################
