####################################
# Start Substitutions
####################################

substitutions:
# Specify below pin numbers for UART, GPIO, and I2C connections
# Default values are set for the ESP32-S3 Zero
# Add superseding substitutions in your specific device configuration if these don't match the actual pins used.

  tx_pin_uart: GPIO17
  rx_pin_uart: GPIO16
  light_gpio: GPIO2
  mic_adc: GPIO36
  motion_gpio: GPIO13
  sda_pin_i2c: GPIO21
  scl_pin_i2c: GPIO22

####################################
# End Substitutions
####################################

esphome:
  platformio_options:
    board_build.flash_mode: dio
    board_build.flash_size: 4MB
    board_build.f_flash: 40000000L

esp32:
  board: wemos_d1_mini32
  variant: esp32
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      # ESSENTIAL BLUETOOTH ENABLEMENT
      CONFIG_BT_ENABLED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      
      # MEMORY OPTIMIZATIONS
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_LOG_DEFAULT_LEVEL_WARN: y
      CONFIG_LOG_MAXIMUM_LEVEL_WARN: y
      
      # TASK OPTIMIZATIONS
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"
      CONFIG_ESP_MAIN_TASK_STACK_SIZE: "3584"
      CONFIG_ESP_TIMER_TASK_STACK_SIZE: "3072"

uart:
  id: uart_bus
  tx_pin: 
    number: ${tx_pin_uart}
#    mode:
#      input: true
#      pullup: true
  rx_pin: 
    number: ${rx_pin_uart}
#    mode:
#      input: true
#      pullup: true
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
#  data_bits: 8
