####################################
# Start Substitutions
####################################

substitutions:
# Specify below pin numbers for UART, GPIO, and I2C connections
# Default values are set for the ESP32-S3 Zero
# Add superseding substitutions in your specific device configuration if these don't match the actual pins used.

  tx_pin_uart: GPIO17
  rx_pin_uart: GPIO16
  light_gpio: GPIO2
  mic_adc: GPIO36
  motion_gpio: GPIO13
  sda_pin_i2c: GPIO21
  scl_pin_i2c: GPIO22

####################################
# End Substitutions
####################################

esphome:
  platformio_options:
    board_build.flash_mode: dio
    board_build.flash_size: 4MB
    board_build.f_flash: 40000000L

esp32:
  board: wemos_d1_mini32
  variant: esp32
  flash_size: 4MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      # MEMORY OPTIMIZATIONS (Critical for BLE + smaller ESP32)
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y         # Optimize for size, not performance
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
      
      # LOGGING OPTIMIZATIONS (Major memory saver)
      CONFIG_LOG_DEFAULT_LEVEL_WARN: y             # Reduce log verbosity
      CONFIG_LOG_MAXIMUM_LEVEL_WARN: y             # Limit max log level
      CONFIG_LOG_COLORS: n                         # Disable colored logs
      
      # BLE MEMORY OPTIMIZATIONS (Enhanced for D1 Mini)
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: y          # Dynamic BLE memory allocation
      CONFIG_BT_BLE_HOST_QUEUE_CONG_CHECK: y       # BLE queue congestion check
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y       # BLE 4.2 support
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y       # BLE 5.0 support
      CONFIG_BT_NIMBLE_ENABLED: y                  # Use NimBLE stack (lighter)
      CONFIG_BT_NIMBLE_MAX_CONNECTIONS: "3"        # Limit connections for memory
      
      # TASK AND MEMORY OPTIMIZATIONS (Tuned for D1 Mini)
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"          # Watchdog timeout
      CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE: "2048"  # Reduce event task stack
      CONFIG_ESP_MAIN_TASK_STACK_SIZE: "3584"      # Reduce main task stack
      CONFIG_ESP_TIMER_TASK_STACK_SIZE: "3072"     # Reduce timer task stack
      CONFIG_FREERTOS_UNICORE: y                   # Use single core mode for better BLE performance
      
      # WIFI OPTIMIZATIONS (Balanced for BLE coexistence)
      CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM: "6" # Reduced WiFi RX buffers
      CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER_NUM: "12" # Reduced WiFi TX buffers
      CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM: "3"  # Reduce static RX buffers
      CONFIG_ESP32_WIFI_AMPDU_TX_ENABLED: n        # Disable WiFi AMPDU for better BLE
      CONFIG_ESP32_WIFI_AMPDU_RX_ENABLED: n        # Disable WiFi AMPDU for better BLE
      
      # DISABLE UNUSED FEATURES
      CONFIG_ESP_CONSOLE_UART_NONE: y              # Disable console UART
      CONFIG_ESP32_ENABLE_COREDUMP: n              # Disable core dumps
      CONFIG_ESP32_PHY_CALIBRATION_AND_DATA_STORAGE: n  # Disable PHY calibration storage
      CONFIG_ESP32_TIME_SYSCALL_USE_RTC_FRC1: y    # Use RTC for time syscalls
      
      # BLUETOOTH SPECIFIC OPTIMIZATIONS
      CONFIG_BT_CONTROLLER_ONLY: n                 # Enable full Bluetooth stack
      CONFIG_BT_ENABLED: y
      CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_EXTERNAL: y  # Use external memory allocation
      CONFIG_BT_NIMBLE_MSYS_1_BLOCK_COUNT: "12"    # Optimize memory blocks
      CONFIG_BT_NIMBLE_ACL_BUF_COUNT: "10"         # Optimize ACL buffers

uart:
  id: uart_bus
  tx_pin: 
    number: ${tx_pin_uart}
#    mode:
#      input: true
#      pullup: true
  rx_pin: 
    number: ${rx_pin_uart}
#    mode:
#      input: true
#      pullup: true
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
#  data_bits: 8
