####################################
# Start Substitutions
####################################

substitutions:
# Specify below pin numbers for UART, GPIO, and I2C connections
# Default values are set for the ESP32-Cs Super Mini
# Add superseding substitutions in your specific device configuration if these don't match the actual pins used.

  tx_pin_uart: GPIO21
  rx_pin_uart: GPIO20
  light_gpio: GPIO4
  mic_adc: GPIO0
  motion_gpio: GPIO10
  sda_pin_i2c: GPIO8
  scl_pin_i2c: GPIO9

####################################
# End Substitutions
####################################

esphome:
  platformio_options:
    board_build.flash_mode: dio
    board_build.flash_size: 4MB
    board_build.f_flash: 40000000L


esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  flash_size: 4MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      # Performance optimizations
      # CONFIG_COMPILER_OPTIMIZATION_PERF: y
      # CONFIG_COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

      # Compiler optimizations (balanced approach)
      CONFIG_COMPILER_OPTIMIZATION_SIZE: "y"
      # Note: Removed PERF optimization as it can cause instability on ESP32 Pico
      
      # Memory management
      # CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM: "4"
      # CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM: "8"
      # CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER_NUM: "8"
      CONFIG_ESP32_WIFI_AMPDU_TX_ENABLED: "y"
      CONFIG_ESP32_WIFI_AMPDU_RX_ENABLED: "y"

      # WiFi compatibility options for WPA3/mesh networks
      CONFIG_ESP32_WIFI_ENABLE_WPA3_SAE: n
      CONFIG_ESP32_WIFI_ENABLE_WPA3_OWE_STA: n
      CONFIG_ESP32_WIFI_SOFTAP_SAE_SUPPORT: n

      # Task and system stability
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"
      CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU0: "y"
      CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU1: "y"
      CONFIG_ESP_INT_WDT_TIMEOUT_MS: "800"
      CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE: "4096"
      
      # Power management for stability
      CONFIG_PM_ENABLE: "y"
      CONFIG_PM_DFS_INIT_AUTO: "y"
      
      # Network stack optimizations
      CONFIG_LWIP_TCP_MSS: "1436"
      CONFIG_LWIP_TCP_RECVMBOX_SIZE: "32"
      CONFIG_LWIP_UDP_RECVMBOX_SIZE: "32"
      CONFIG_LWIP_TCPIP_RECVMBOX_SIZE: "32"

      # BLE 4.2 is supported by ALL ESP32 boards that have bluetooth, the original and derivatives.
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      # Also enable this on any derivative boards (S2, C3 etc) but not the original ESP32.
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      # Extend the watchdog timeout, so the device reboots if the device appears locked up for over 10 seconds.
      # CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"
    
uart:
  id: uart_bus
  tx_pin: ${tx_pin_uart}
  rx_pin: ${rx_pin_uart}
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
#  data_bits: 8

light:
  - platform: binary
    name: "Blue Status Light"
    output: light_output
    id: status_light
    restore_mode: ALWAYS_OFF
 
output:
  - platform: gpio
    pin: ${light_gpio}
    id: light_output
