esphome:
  platformio_options:
    board_build.flash_mode: dio
    board_build.flash_size: 4MB
    board_build.f_flash: 40000000L
  on_boot:
    priority: 600
    then:
      - delay: 500ms  # Boot delay for sensor stabilization

esp32:
  board: nodemcu-32s
  variant: esp32
  flash_size: 4MB
  framework:
    type: arduino
    version: recommended


# esphome:
#   on_boot:
#     priority: 600
#     then:
#       - delay: 500ms  # Boot delay for sensor stabilization

# esp32:
#   board: esp32dev
#   framework:
#     type: arduino
    
light:
  - platform: binary
    name: "Blue Status Light"
    output: light_output
    id: status_light
    #restore_mode: ALWAYS_ON
    restore_mode: RESTORE_DEFAULT_ON
    #restore_mode: ALWAYS_OFF
 
output:
  - platform: gpio
    pin: ${light_gpio}
    id: light_output

