####################################
# Start Substitutions
####################################

substitutions:
# Specify below pin numbers for UART, GPIO, and I2C connections
# Default values are set for the ESP32-C6 Zero
# Add superseding substitutions in your specific device configuration if these don't match the actual pins used.

  tx_pin_uart: GPIO5
  rx_pin_uart: GPIO4
  light_gpio: GPIO8
  mic_adc: GPIO2
  motion_gpio: GPIO7
  sda_pin_i2c: GPIO21
  scl_pin_i2c: GPIO22

####################################
# End Substitutions
####################################

esphome:
  platformio_options:
    board_build.flash_mode: qio
    board_build.f_flash: 80000000L

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf
    version: latest
    sdkconfig_options:
      # Performance optimizations
      CONFIG_COMPILER_OPTIMIZATION_PERF: y
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
      # BLE support - ESP32-C6 supports BLE 5.0+
      CONFIG_BT_ENABLED: y
      CONFIG_BT_BLE_ENABLED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      # Extend the watchdog timeout
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"
      # USB CDC On Boot - ESP32-C6 has native USB Serial/JTAG
      CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG: y
      CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG_ENABLED: y
      # WiFi 6 compatibility options
      CONFIG_ESP_WIFI_ENABLE_WPA3_SAE: y
      CONFIG_ESP_WIFI_SOFTAP_SAE_SUPPORT: y
      CONFIG_ESP_WIFI_ENABLE_WPA3_OWE_STA: y
      # WiFi optimization
      CONFIG_ESP_WIFI_SW_COEXIST_ENABLE: y
      # Power management optimization
      CONFIG_PM_ENABLE: n
      # ESP32-C6 specific optimizations
      CONFIG_ESP_PHY_ENABLE_USB: y
      CONFIG_ESP_SYSTEM_PANIC_PRINT_REBOOT: y    


uart:
  id: uart_bus
  tx_pin: ${tx_pin_uart}
  rx_pin: ${rx_pin_uart}
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
#  data_bits: 8

light:
  - platform: binary
    name: "Blue Status Light"
    output: light_output
    id: status_light
    #restore_mode: ALWAYS_ON
    restore_mode: RESTORE_DEFAULT_ON
    #restore_mode: ALWAYS_OFF
 
output:
  - platform: gpio
    pin: ${light_gpio}
    id: light_output
