####################################
# Start Substitutions
####################################

substitutions:
# Specify below pin numbers for UART, GPIO, and I2C connections
# Default values are set for the Seeed XIAO ESP32-S3
# Add superseding substitutions in your specific device configuration if these don't match the actual pins used.

  tx_pin_uart: GPIO43
  rx_pin_uart: GPIO44
  light_gpio: GPIO21
  mic_adc: GPIO36
  motion_gpio: GPIO5
  sda_pin_i2c: GPIO5
  scl_pin_i2c: GPIO6

####################################
# End Substitutions
####################################

# Configuration for ESPHome settings and options
esphome:
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM  # Enable PSRAM support for additional memory
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio
  on_boot:
    priority: 600
    then:
      - delay: 500ms  # Boot delay for sensor stabilization

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: latest

# Enable logging at DEBUG level for detailed output during development
# Default is INFO
# To disable logging, set baud_rate to 0
logger:
# level: DEBUG
  baud_rate: 0
#  baud_rate: 0

# Set all GPIO pins substitutions in device configuration
i2c:
  sda: "${sda_pin_i2c}"
  scl: "${scl_pin_i2c}"
  scan: true
  frequency: 400kHz  # Optimal frequency for BME680

uart:
  id: uart_bus
  tx_pin: 
    number: ${tx_pin_uart}
  rx_pin: 
    number: ${rx_pin_uart}
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

Only enable the following if the device has a light
light:
  - platform: binary
    name: "Blue Status Light"
    output: light_output
    id: led_light
    restore_mode: ALWAYS_OFF
 
output:
  - platform: gpio
    pin: ${light_gpio}
    id: light_output
