########################################
# GUPPI.ST-OCC-GP-2410-BLE-DEFAULTS.yaml
# Default setting for basic single-target occupancy sensors with BLE tracker capabilities
########################################

####################################
# Start Substitutions
####################################

substitutions:
  # Update the comment_text, project_name, and project_version information to match the device
  comment_text: "Generally Unstable and Poorly Planned Implementations - Bluetooth Tracker"
  project_name: "GUPPI.BLE"
  project_version: "25.6.14.1"

####################################
# End Substitutions
####################################

esphome:
  comment: "${comment_text}"
  project: 
    name: "${project_name}"
    version: "${project_version}"

logger:
#  level: WARN
  level: INFO
#  baud_rate: 0  # Disable UART logging to save memory
  # 0 Enables logging, but disables serial-port logging to free CPU and memory

debug:
  update_interval: 30s

ota:
  - platform: esphome

# Web server (optional, consider disabling in production)
web_server:
  port: 80
#  include_internal: false  # Don't include internal sensors
##  local: true             # Disable mDNS
#  ota: false             # Disable OTA via web server


