########################################
# GUPPI.ST-OCC-GP-2410-BLE-DEFAULTS.yaml
# Default setting for basic single-target occupancy sensors with BLE tracker capabilities
########################################

####################################
# Start Substitutions
####################################

substitutions:
  # Update the comment_text, project_name, and project_version information to match the device
  comment_text: "Generally Unstable and Poorly Planned Implementations - Single-target Human Presence and Occupancy Sensor (ESP32/LD2410)"
  project_name: "GUPPI.ST-OCC-GP-2410"
  project_version: "25.6.20.1"

####################################
# End Substitutions
####################################

esphome:
  comment: "${comment_text}"
  project: 
    name: "${project_name}"
    version: "${project_version}"

# Enable logging at DEBUG level for detailed output during development
logger:
  # 0 Enables logging, but disables serial-port logging to free CPU and memory
  # baud_rate: 0
  #  Disable DEBUG after testing
  #level: INFO

debug:
  update_interval: 30s

ota:
  - platform: esphome

# Web server (optional, consider disabling in production)
web_server:
  port: 80
  version: 3


