####################################
# Start Substitutions
####################################

substitutions:
# Specify below pin numbers for UART, GPIO, and I2C connections
# Delete if not needed
  tx_pin_uart: GPIO21
  rx_pin_uart: GPIO20
  light_gpio: GPIO8
  motion_gpio: GPIO4
  sda_pin_i2c: GPIO6
  scl_pin_i2c: GPIO7

####################################
# End Substitutions
####################################

# Define external packages that ESPHome will fetch at compile time.
# Uncomment the dependencies you need, and add any additional ones you require.
# Delete any dependencies you don't need.
packages:
  project_configs: 
    url: https://github.com/min-con/guppi_occ
    files: [defaults/GUPPI.ST-OCC-GP-2410-BLE-DEFAULTS.yaml, shared-configs/boards/seeed_xiao_esp32c3-esp-idf.yaml, shared-configs/defaults/entity-defaults.yaml, shared-configs/network/wifi.yaml, shared-configs/network/bletracker.yaml, shared-configs/components/ld2410.yaml]
    ref: main
    refresh: 60s

esphome:
  name: guppi-hps-test-02
  friendly_name: Entryway Occupancy Sensor

# Enable Home Assistant API
api:
  encryption:
    key: "xEz+oo6bmpre2anki1g5d38ENE3YOpGZ64Ng1GqeHnQ="

ota:
  - platform: esphome
    id: ota_esphome
    password: "3a2475218149b7b2d9075526053f68d2"

