# Define external packages that ESPHome will fetch at compile time.
# Add/change the dependencies you need.
# Delete any dependencies you don't need.
# EXAMPLE:
packages:
  project_configs: 
#    url: github://min-con/guppi_occ
    url: https://github.com/min-con/guppi_occ
    files: [defaults/GUPPI.ST-OCC-GP-2410-BLE-DEFAULTS.yaml, shared-configs/boards/seeed_xiao_esp32c3-esp-idf.yaml, shared-configs/network/wifi.yaml, shared-configs/network/bletracker.yaml]
    ref: main
    refresh: 0s

esphome:
  name: lukes-office-ble-tracker
  friendly_name: "Luke's Office BLE Tracker"


# Enable Home Assistant API
api:
  encryption:
    key: "lp2ez5/dTzyQbYgaH4Kq+dWP3/5DWiBp/gdQILW96YI="

