####################################
# Start Substitutions
####################################

substitutions:
# Specify below pin numbers for UART, GPIO, and I2C connections
# Delete if not needed
  tx_pin_uart: GPIO43
  rx_pin_uart: GPIO44
  light_gpio: GPIO21
  motion_gpio: GPIO3
  sda_pin_i2c: GPIO5
  scl_pin_i2c: GPIO6

####################################
# End Substitutions
####################################
# Define external packages that ESPHome will fetch at compile time.
# Add/change the dependencies you need.
# Delete any dependencies you don't need.
packages:
  project_configs: 
    url: https://github.com/min-con/guppi_occ
    files: [defaults/GUPPI.ST-OCC-GP-2410-AQI-DEFAULTS.yaml, shared-configs/boards/seeed_xiao_esp32s3-arduino.yaml, shared-configs/network/wifi.yaml, shared-configs/components/ld2410.yaml, shared-configs/components/bme680.yaml,shared-configs/components/bh1750.yaml]
    ref: main
    refresh: 60s

esphome:
  name: lukes-office-occupancy
  friendly_name: "Luke's Office Occupancy"
  comment: "${comment_text}"
  project: 
    name: "${project_name}"
    version: "${project_version}"

# Enable Home Assistant API
api:
  encryption:
    key: "2VoXQZN8mKj1KIKpxDJMalhfteFmoaNf5sUYsgf0FNc="

