wifi:
# # Enable only if using multiple networks.
#   networks:
#   - ssid: !secret wifi_ssid
#     password: !secret wifi_password
#   - ssid: !secret wifi_2_ssid # Remove if you only have one network
#     password: !secret wifi_2_password # Remove if you only have one network
#   reboot_timeout: 5min
#   output_power: 8.5dB

# Enable only if using single network.
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 5min
  output_power: 8.5dB
  fast_connect: True # Only usable with one network
  power_save_mode: LIGHT # Optional, default is LIGHT

# Enable only if using static IP address
  # manual_ip:
  #   static_ip: !secret static_ip
  #   gateway: !secret gateway
  #   subnet: !secret subnet
  #   dns1: !secret dns1
  #   dns2: !secret dns2 

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name}"
    password: !secret fallback_ap_password

captive_portal:

sensor:
  # WiFi signal strength sensor
  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

text_sensor:
  # Device IP Address
  - platform: wifi_info
    ip_address:
      name: "IP Address"
#      id: "ip"
      icon: "mdi:ip-network"
      entity_category: diagnostic
    mac_address:
      name: "MAC Address"
#      id: "mac_address"
      entity_category: "diagnostic"
      icon: mdi:ip-network
    ssid:
      name: Connected SSID
      entity_category: diagnostic
    bssid:
      name: Connected BSSID
      entity_category: diagnostic
    scan_results:
      name: Latest Scan Results
      entity_category: diagnostic
    dns_address:
      name: DNS Address  
      entity_category: diagnostic
  
