# LD2450 Configuration
# Basic ESPHome configuration is assumed to be defined elsewhere (esphome, esp32, logger, api, ota, wifi)
# UART configuration is required:
# uart:
#   id: uart_bus
#   tx_pin: GPIO17  # Adjust according to your wiring
#   rx_pin: GPIO16  # Adjust according to your wiring
#   baud_rate: 256000
#   parity: NONE
#   stop_bits: 1
#   data_bits: 8

# LD2450 Component
ld2450:
  throttle: 100ms
  id: ld2450_radar
  uart_id: uart_bus

# User configurable radar configuration parameters
number:
  - platform: ld2450
    ld2450_id: ld2450_radar
    # Presence timeout (similar to LD2410's timeout)
    presence_timeout:
      id: timeout
      name: Timeout
      icon: "mdi:timer-outline"
      unit_of_measurement: "s"
      entity_category: CONFIG
    
    # Zone 1 configuration (X/Y coordinates instead of just distance)
    zone_1:
      x1:
        name: "Zone 1 X1"
        id: z1_x1
        unit_of_measurement: "cm"
        icon: "mdi:axis-x-arrow"
        entity_category: CONFIG
      y1:
        name: "Zone 1 Y1"
        id: z1_y1
        unit_of_measurement: "cm"
        icon: "mdi:axis-y-arrow"
        entity_category: CONFIG
      x2:
        name: "Zone 1 X2"
        id: z1_x2
        unit_of_measurement: "cm"
        icon: "mdi:axis-x-arrow"
        entity_category: CONFIG
      y2:
        name: "Zone 1 Y2"
        id: z1_y2
        unit_of_measurement: "cm"
        icon: "mdi:axis-y-arrow"
        entity_category: CONFIG

    # Zone 2 configuration
    zone_2:
      x1:
        name: "Zone 2 X1"
        id: z2_x1
        unit_of_measurement: "cm"
        icon: "mdi:axis-x-arrow"
        entity_category: CONFIG
      y1:
        name: "Zone 2 Y1"
        id: z2_y1
        unit_of_measurement: "cm"
        icon: "mdi:axis-y-arrow"
        entity_category: CONFIG
      x2:
        name: "Zone 2 X2"
        id: z2_x2
        unit_of_measurement: "cm"
        icon: "mdi:axis-x-arrow"
        entity_category: CONFIG
      y2:
        name: "Zone 2 Y2" 
        id: z2_y2
        unit_of_measurement: "cm"
        icon: "mdi:axis-y-arrow"
        entity_category: CONFIG

    # Zone 3 configuration
    zone_3:
      x1:
        name: "Zone 3 X1"
        id: z3_x1
        unit_of_measurement: "cm"
        icon: "mdi:axis-x-arrow"
        entity_category: CONFIG
      y1:
        name: "Zone 3 Y1"
        id: z3_y1
        unit_of_measurement: "cm"
        icon: "mdi:axis-y-arrow"
        entity_category: CONFIG
      x2:
        name: "Zone 3 X2"
        id: z3_x2
        unit_of_measurement: "cm"
        icon: "mdi:axis-x-arrow"
        entity_category: CONFIG
      y2:
        name: "Zone 3 Y2"
        id: z3_y2
        unit_of_measurement: "cm"
        icon: "mdi:axis-y-arrow"
        entity_category: CONFIG

  # Custom template numbers for additional functionality
  - platform: template
    name: "Zone 1 Distance Threshold"
    id: z1_distance_threshold
    device_class: distance
    min_value: 0
    max_value: 800
    step: 10
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 200
    icon: "mdi:radar"
    entity_category: CONFIG
    unit_of_measurement: "cm"

  - platform: template
    name: "Zone 2 Distance Threshold"
    id: z2_distance_threshold
    device_class: distance
    min_value: 0
    max_value: 800
    step: 10
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 400
    icon: "mdi:radar"
    entity_category: CONFIG
    unit_of_measurement: "cm"

  - platform: template
    name: "Zone 3 Distance Threshold"
    id: z3_distance_threshold
    device_class: distance
    min_value: 0
    max_value: 800
    step: 10
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 600
    icon: "mdi:radar"
    entity_category: CONFIG
    unit_of_measurement: "cm"

sensor:
  # LD2450 radar sensor readings
  - platform: ld2450
    ld2450_id: ld2450_radar
    
    # Count sensors
    target_count:
      name: "Target Count"
      id: target_count
      icon: "mdi:account-multiple"
    still_target_count:
      name: "Still Target Count"
      id: still_target_count
      icon: "mdi:account-multiple"
    moving_target_count:
      name: "Moving Target Count" 
      id: moving_target_count
      icon: "mdi:account-multiple"
    
    # Target 1 data
    target_1:
      x:
        name: "Target 1 X"
        id: target_1_x
        unit_of_measurement: "cm"
        icon: "mdi:axis-x-arrow"
      y:
        name: "Target 1 Y" 
        id: target_1_y
        unit_of_measurement: "cm"
        icon: "mdi:axis-y-arrow"
      speed:
        name: "Target 1 Speed"
        id: target_1_speed
        unit_of_measurement: "cm/s"
        icon: "mdi:speedometer"
      distance:
        name: "Target 1 Distance"
        id: target_1_distance
        unit_of_measurement: "cm"
        icon: "mdi:radar"
      angle:
        name: "Target 1 Angle"
        id: target_1_angle
        unit_of_measurement: "°"
        icon: "mdi:angle-acute"
      resolution:
        name: "Target 1 Resolution"
        id: target_1_resolution
        unit_of_measurement: "cm"
        icon: "mdi:ruler"
    
    # Target 2 data
    target_2:
      x:
        name: "Target 2 X"
        id: target_2_x
        unit_of_measurement: "cm"
        icon: "mdi:axis-x-arrow"
      y:
        name: "Target 2 Y"
        id: target_2_y
        unit_of_measurement: "cm"
        icon: "mdi:axis-y-arrow"
      speed:
        name: "Target 2 Speed"
        id: target_2_speed
        unit_of_measurement: "cm/s"
        icon: "mdi:speedometer"
      distance:
        name: "Target 2 Distance"
        id: target_2_distance
        unit_of_measurement: "cm"
        icon: "mdi:radar"
      angle:
        name: "Target 2 Angle"
        id: target_2_angle
        unit_of_measurement: "°"
        icon: "mdi:angle-acute"
      resolution:
        name: "Target 2 Resolution"
        id: target_2_resolution
        unit_of_measurement: "cm"
        icon: "mdi:ruler"
    
    # Target 3 data
    target_3:
      x:
        name: "Target 3 X"
        id: target_3_x
        unit_of_measurement: "cm"
        icon: "mdi:axis-x-arrow"
      y:
        name: "Target 3 Y"
        id: target_3_y
        unit_of_measurement: "cm"
        icon: "mdi:axis-y-arrow"
      speed:
        name: "Target 3 Speed"
        id: target_3_speed
        unit_of_measurement: "cm/s"
        icon: "mdi:speedometer"
      distance:
        name: "Target 3 Distance"
        id: target_3_distance
        unit_of_measurement: "cm"
        icon: "mdi:radar"
      angle:
        name: "Target 3 Angle"
        id: target_3_angle
        unit_of_measurement: "°"
        icon: "mdi:angle-acute"
      resolution:
        name: "Target 3 Resolution"
        id: target_3_resolution
        unit_of_measurement: "cm"
        icon: "mdi:ruler"
    
    # Zone target count sensors
    zone_1:
      target_count:
        name: "Zone 1 Target Count"
        id: zone_1_target_count
        icon: "mdi:account-multiple"
      still_target_count:
        name: "Zone 1 Still Target Count"
        id: zone_1_still_target_count
        icon: "mdi:account-multiple"
      moving_target_count:
        name: "Zone 1 Moving Target Count"
        id: zone_1_moving_target_count
        icon: "mdi:account-multiple"
    
    zone_2:
      target_count:
        name: "Zone 2 Target Count"
        id: zone_2_target_count
        icon: "mdi:account-multiple"
      still_target_count:
        name: "Zone 2 Still Target Count"
        id: zone_2_still_target_count
        icon: "mdi:account-multiple"
      moving_target_count:
        name: "Zone 2 Moving Target Count"
        id: zone_2_moving_target_count
        icon: "mdi:account-multiple"
    
    zone_3:
      target_count:
        name: "Zone 3 Target Count"
        id: zone_3_target_count
        icon: "mdi:account-multiple"
      still_target_count:
        name: "Zone 3 Still Target Count"
        id: zone_3_still_target_count
        icon: "mdi:account-multiple"
      moving_target_count:
        name: "Zone 3 Moving Target Count"
        id: zone_3_moving_target_count
        icon: "mdi:account-multiple"
  
  # Additional sensor for calculated values (similar to LD2410 moving/still energy)
  - platform: template
    name: "Closest Target Distance"
    id: closest_target_distance
    device_class: distance
    unit_of_measurement: "cm"
    icon: "mdi:radar"
    lambda: |-
      float min_distance = 999.0;
      if (id(target_1_distance).state > 0 && id(target_1_distance).state < min_distance) {
        min_distance = id(target_1_distance).state;
      }
      if (id(target_2_distance).state > 0 && id(target_2_distance).state < min_distance) {
        min_distance = id(target_2_distance).state;
      }
      if (id(target_3_distance).state > 0 && id(target_3_distance).state < min_distance) {
        min_distance = id(target_3_distance).state;
      }
      if (min_distance < 999.0) {
        return min_distance;
      } else {
        return NAN;
      }
    
  - platform: template
    name: "Fastest Target Speed"
    id: fastest_target_speed
    unit_of_measurement: "cm/s"
    icon: "mdi:speedometer"
    lambda: |-
      float max_speed = 0.0;
      if (id(target_1_speed).state > max_speed) {
        max_speed = id(target_1_speed).state;
      }
      if (id(target_2_speed).state > max_speed) {
        max_speed = id(target_2_speed).state;
      }
      if (id(target_3_speed).state > max_speed) {
        max_speed = id(target_3_speed).state;
      }
      if (max_speed > 0.0) {
        return max_speed;
      } else {
        return NAN;
      }

binary_sensor:
  # LD2450 radar binary sensors - similar naming to LD2410
  - platform: ld2450
    ld2450_id: ld2450_radar
    has_target:
      name: "Target Detected"
      id: has_target
      device_class: occupancy
      icon: "mdi:motion-sensor"
    has_moving_target:
      name: "Moving Target Detected"
      id: has_moving_target
      device_class: motion
      icon: "mdi:motion-sensor"
    has_still_target:
      name: "Still Target Detected"
      id: has_still_target
      device_class: occupancy
      icon: "mdi:radar"

  # Zone presence sensors - updated for LD2450's capability
  - platform: template
    name: "Zone 1 Presence"
    id: zone_1_presence
    device_class: presence
    icon: "mdi:motion-sensor"
    lambda: |-
      return id(zone_1_target_count).state > 0;
  
  - platform: template
    name: "Zone 2 Presence"
    id: zone_2_presence
    device_class: presence
    icon: "mdi:motion-sensor"
    lambda: |-
      return id(zone_2_target_count).state > 0;
  
  - platform: template
    name: "Zone 3 Presence"
    id: zone_3_presence
    device_class: presence
    icon: "mdi:motion-sensor"
    lambda: |-
      return id(zone_3_target_count).state > 0;

  # Additional distance-based presence sensors (similar to LD2410 implementation)
  - platform: template
    name: "Distance Zone 1 Presence"
    id: distance_zone_1_presence
    device_class: presence
    icon: "mdi:motion-sensor"
    lambda: |-
      if (id(has_target).state && id(closest_target_distance).state < id(z1_distance_threshold).state) {
        return true;
      } else {
        return false;
      }
  
  - platform: template
    name: "Distance Zone 2 Presence"
    id: distance_zone_2_presence
    device_class: presence
    icon: "mdi:motion-sensor"
    lambda: |-
      if (id(has_target).state && 
          id(closest_target_distance).state >= id(z1_distance_threshold).state && 
          id(closest_target_distance).state < id(z2_distance_threshold).state) {
        return true;
      } else {
        return false;
      }
  
  - platform: template
    name: "Distance Zone 3 Presence"
    id: distance_zone_3_presence
    device_class: presence
    icon: "mdi:motion-sensor"
    lambda: |-
      if (id(has_target).state && 
          id(closest_target_distance).state >= id(z2_distance_threshold).state && 
          id(closest_target_distance).state < id(z3_distance_threshold).state) {
        return true;
      } else {
        return false;
      }

  # Composite presence sensor
  - platform: template
    name: "Presence Detected"
    id: has_presence
    device_class: presence
    icon: "mdi:motion-sensor"
    lambda: |-
      return id(has_target).state || id(has_moving_target).state || id(has_still_target).state;

text_sensor:
  # LD2450 radar text sensors
  - platform: ld2450
    ld2450_id: ld2450_radar
    
    # Firmware version (similar to LD2410)
    version:
      name: "Radar Firmware Version"
      id: radar_firmware
      entity_category: diagnostic
    
    # Bluetooth MAC address (similar to LD2410)
    mac_address:
      name: "Radar MAC Address"
      id: radar_mac
      entity_category: diagnostic
    
    # Target direction sensors
    target_1:
      direction:
        name: "Target 1 Direction"
        id: target_1_direction
        icon: "mdi:compass"
    
    target_2:
      direction:
        name: "Target 2 Direction"
        id: target_2_direction
        icon: "mdi:compass"
    
    target_3:
      direction:
        name: "Target 3 Direction"
        id: target_3_direction
        icon: "mdi:compass"

button:
  # LD2450 radar buttons
  - platform: ld2450
    ld2450_id: ld2450_radar
    
    # Factory reset button (similar to LD2410)
    factory_reset:
      name: "Factory Reset Radar"
      id: factory_reset
      icon: "mdi:restore"
      entity_category: config
    
    # Restart button (similar to LD2410)
    restart:
      name: "Restart Radar"
      id: restart_radar
      icon: "mdi:restart"
      entity_category: config

switch:
  # LD2450 radar switches
  - platform: ld2450
    ld2450_id: ld2450_radar
    
    # Bluetooth switch (similar to LD2410)
    bluetooth:
      name: "Radar Bluetooth"
      id: bluetooth
      icon: "mdi:bluetooth"
      entity_category: config
    
    # Multi-target tracking (LD2450 specific)
    multi_target:
      name: "Multi-Target Tracking"
      id: multi_target
      icon: "mdi:account-group"
      entity_category: config

select:
  # LD2450 radar selects
  - platform: ld2450
    ld2450_id: ld2450_radar
    
    # Baud rate selection (similar to LD2410)
    baud_rate:
      name: "Baud Rate"
      id: baud_rate
      icon: "mdi:serial-port"
      entity_category: config
    
    # Zone type selection (LD2450 specific)
    zone_type:
      name: "Zone Type"
      id: zone_type
      icon: "mdi:map-marker-radius"
      entity_category: config